language: cpp

sudo: true

compiler: gcc

branches:
  except:  # do not build tags that we create using the upload.sh script
    - /^(?i:continuous.*)$/

jobs:
  include:
    - stage: build-osx
      os:
        - osx
      osx_image: xcode9.0
      addons:
        homebrew:
          update: true
      script:
        - ./travisHomeBrewDoItAll
        - pdf2htmlEX --version
