#!/bin/bash

# This bash script builds everyting on an TravisCI Mac OSx worker

# See:
# https://docs.travis-ci.com/user/installing-dependencies/#using-homebrew-without-addon-on-older-macos-images
# For details on obtaining/using the correct ruby version for homebrew.

echo "-------------------------------------------------"
echo $PATH
echo $LDFLAGS
echo $CPPFLAGS
which clang
ls -la $(which clang)
clang --version
echo "-------------------------------------------------"
brew tap pdf2htmlEX/homebrew-brewTap
brew update
echo "-------------------------------------------------"
echo $PATH
echo $LDFLAGS
echo $CPPFLAGS
which clang
ls -la $(which clang)
clang --version
echo "-------------------------------------------------"
brew install llvm
brew install -v python@2
brew install jq
echo "-------------------------------------------------"
echo $PATH
echo $LDFLAGS
echo $CPPFLAGS
which clang
ls -la $(which clang)
clang --version
export llvmVersion=$(brew info --json=v1 llvm | jq '.[].installed[].version' | tr -d '"')
echo "brew llvm version: $llvmVersion"
export python2Version=$(brew info --json=v1 python@2 | jq '.[].installed[].version' | tr -d '"')
echo "brew python@2 version: $python2Version"
echo "-------------------------------------------------"
brew info llvm
brew switch llvm $llvmVersion
brew info python@2
brew switch python@2 $python2Version
echo "-------------------------------------------------"
echo $PATH
echo $LDFLAGS
echo $CPPFLAGS
which clang
ls -la $(which clang)
clang --version
which python
ls -la $(which python)
python --version
echo "-------------------------------------------------"
brew install -v fontforge@20170731
#brew install -v pdf2htmlex-new
echo "-------------------------------------------------"
echo $PATH
echo $LDFLAGS
echo $CPPFLAGS
which clang
ls -la $(which clang)
which python
ls -la $(which python)
python --version
export fontForgeVersion=$(brew info --json=v1 fontforge@20170731 | jq '.[].installed[].version' | tr -d '"')
echo "fontForge version: $fontForgeVersion"
brew switch fontforge@20170731 $fontForgeVersion
which fontforge
fontforge --version
which pdf2htmlEX
ls -la $(which pdf2htmlEX)
otool -L $(which fontforge)
#pdf2htmlEX --version
echo "-------------------------------------------------"
