context("Test the model bulding interface between R and C")

test_that("C_newSpeciesTable creates a species table in C", {
  test <- .C_newSpeciesTable(10)
  expect_false(is.null(test))
  expect_true(.C_isSpeciesTable(test))
})

test_that("C_numSpecies reports the correct number of species for a species table", {
  test <- .C_newSpeciesTable(10)
  expect_equal(.C_numSpecies(test), 10)
})

test_that("C_getSpeciesValues gets the correct values", {
  test <- .C_newSpeciesTable(10)
  expect_error(.C_setSpeciesValues(test, 50, c(0.1, 0.2, 1.0, 0.3, 0.4)))
  expect_true(.C_setSpeciesValues(test, 5, c(0.1, 0.2, 1.0, 0.4, 0.5)))
  expect_true(.C_setSpeciesValues(test, 6, c(0.1, NA_real_, 0.0, 0.4, 0.5)))
  values <- .C_getSpeciesValues(test, 2)
  expect_equal(length(values), 5)
  expect_equal(values[1], NA_real_)
  expect_equal(values[2], NA_real_)
  expect_equal(values[3], 0.0)
  expect_equal(values[4], NA_real_)
  expect_equal(values[5], NA_real_)
  values <- .C_getSpeciesValues(test, 5)
  expect_equal(length(values), 5)
  expect_equal(values[1], 0.1)
  expect_equal(values[2], 0.2)
  expect_equal(values[3], 1.0)
  expect_equal(values[4], 0.4)
  expect_equal(values[5], 0.5)
  values <- .C_getSpeciesValues(test, 6)
  expect_equal(length(values), 5)
  expect_equal(values[1], 0.1)
  expect_equal(values[2], NA_real_)
  expect_equal(values[3], 0.0)
  expect_equal(values[4], 0.4)
  expect_equal(values[5], 0.5)
})

test_that("we can get/set Predator/Prey Coefficients", {
  test <- .C_newSpeciesTable(15)
  expect_error(.C_setPredatorCoefficients(test, 50, c(1, 2), c(0.1, 0.2), c(1.1, 1.2), c(0, 1)))
  expect_error(.C_setPreyCoefficients(test, 50, c(3, 4), c(0.3, 0.4), c(1.3, 1.4), c(10, 11)))
  #
  expect_false(.C_setPredatorCoefficients(test, 2, c(101, 2), c(10.1, 10.2), c(11.1, 11.2), c(20, 21)))
  expect_false(.C_setPreyCoefficients(test, 2, c(103, 4), c(1.3, 1.4), c(2.3, 2.4), c(30, 31)))
  #
  expect_true(.C_setPredatorCoefficients(test, 5, c(5, 6), c(0.5, 0.6), c(1.5, 1.6), c(40, 41)))
  expect_true(.C_setPreyCoefficients(test, 5, c(7, 8), c(0.7, 0.8), c(1.7, 1.8), c(50, 51)))
  #
  expect_true(.C_setPredatorCoefficients(test, 6, c(9, 10), c(0.9, 1.0), c(1.9, 2.0), c(60, 61)))
  expect_true(.C_setPreyCoefficients(test, 6, c(11, 12), c(1.1, 1.2), c(2.1, 2.2), c(70, 71)))
  #
  values <- .C_getPredatorCoefficients(test, 2)
  expect_true(is.null(values))
  #
  values <- .C_getPredatorCoefficients(test, 5)
  expect_false(is.null(values))
  expect_equal(length(values), 4)
  expect_equal(length(values[[1]]), 2)
  expect_equal(values[[1]][1], 5)
  expect_equal(values[[1]][2], 6)
  expect_equal(length(values[[2]]), 2)
  expect_equal(values[[2]][1], 0.5)
  expect_equal(values[[2]][2], 0.6)
  expect_equal(length(values[[3]]), 2)
  expect_equal(values[[3]][1], 1.5)
  expect_equal(values[[3]][2], 1.6)
  expect_equal(length(values[[4]]), 2)
  expect_equal(values[[4]][1], 40)
  expect_equal(values[[4]][2], 41)
  #
  values <- .C_getPreyCoefficients(test, 6)
  expect_false(is.null(values))
  expect_equal(length(values), 4)
  expect_equal(length(values[[1]]), 2)
  expect_equal(values[[1]][1], 11)
  expect_equal(values[[1]][2], 12)
  expect_equal(length(values[[2]]), 2)
  expect_equal(values[[2]][1], 1.1)
  expect_equal(values[[2]][2], 1.2)
  expect_equal(length(values[[3]]), 2)
  expect_equal(values[[3]][1], 2.1)
  expect_equal(values[[3]][2], 2.2)
  expect_equal(length(values[[4]]), 2)
  expect_equal(values[[4]][1], 70)
  expect_equal(values[[4]][2], 71)
})