---
title: "Trophic Logistic Models"
author: "Stephen Gaito"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Trophic Logistic Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

We base the time integration on the Logistic Equation:

\[
\begin{align}
\frac{dR_1}{dt} & = & rR_1(t) \left(1 − \frac{R_1(t)}{k_1} \right) - \frac{aC(t)R_1(t)}{1 + a(R_1(t) + R_2(t))} \\
\frac{dR_2}{dt} & = & rR_2(t) \left(1 − \frac{R_2(t - \tau)}{k_2} \right) - \frac{aC(t)R_2(t)}{1 + a(R_1(t) + R_2(t))} \\
\frac{dC}{dt} & = & C(t) \left(\frac{ea(R_1(t) + R_2(t))}{1 + a(R_1(t) + R_2(t))} - m \right)
\end{align}
\]


To build a given trophic model we begin by creating an empty species table and then adding the different species:

species <- newSpeciesTable()
species <- addSpecies(species, 
  name="resource1",
  growthRate=0.2,
  carryingCapcity=25)
species <- addSpecies(species, 
  name="resource2",
  growthRate=0.2,
  carryingCapcity=25)
species <- addSpecies(species, 
  name="consumer",
  mortality=0.2)

Next we create an empty interactions table and then add some interactions:

interactions <- newInteractionsTable()
interactions <- addInteraction(interactions,
  preditor="consumer",
  prey="resource1",
  attackRate=0.1,
  conversionRate=0.35)
interactions <- addInteraction(interactions,
  preditor="consumer",
  prey="resource2",
  attackRate=0.1,
  conversionRate=0.35)

now we assemble the species and ineractions tables in to a model:

r2c1 <- newModel(species=species, interactions=interactions)

we can then get a LaTeX representation of our model

getLaTeX(r2c1)

or the species interactions in an interactions *matrix* form

getInteractionsMatrix(r2c1)

We might want to specify a random collection of models based upon individual species and interaction mean and standard deviations. To do this we can add species and interactions tables standard deviations tables to the model:

speciesStd <- newSpeciesTable()
speciesStd <- addSpecies(speciesStd, 
  name="resource1",
  growthRate=0.01,
  carryingCapcity=5)
speciesStd <- addSpecies(speciesStd, 
  name="resource2",
  growthRate=0.01,
  carryingCapcity=5)
speciesStd <- addSpecies(speciesStd, 
  name="consumer",
  mortality=0.01)

Next we create an empty interactions table and then add some interactions:

interactionsStd <- newInteractionsTable()
interactionsStd <- addInteraction(interactionsStd,
  preditor="consumer",
  prey="resource1",
  attackRate=0.01,
  conversionRate=0.1)
interactionsStd <- addInteraction(interactionsStd,
  preditor="consumer",
  prey="resource2",
  attackRate=0.01,
  conversionRate=0.1)

This time we can add all four tables to the model at once:

r2c1var <- newModelStd(
  species, speciesStd,
  interactions, interactionsStd
)

To get an individual model:

r2c1 <- varyModel(r2c1var)

